# 貓狗分類器訓練配置文件

# 數據設置
data:
  data_dir: "kaggle_cats_vs_dogs_f"
  batch_size: 32
  num_workers: 4
  image_size: 224
  
# 模型設置  
model:
  architecture: "resnet18"  # 可選: resnet18, resnet34, resnet50, efficientnet_b0
  pretrained: true
  freeze_backbone: true
  num_classes: 2
  
# 訓練設置
training:
  num_epochs: 25
  learning_rate: 0.001
  optimizer: "adam"  # 可選: adam, sgd, adamw
  weight_decay: 0.0001
  scheduler: "step"  # 可選: step, cosine, plateau
  step_size: 7
  gamma: 0.1
  
# 數據增強設置
augmentation:
  train:
    random_resized_crop: true
    random_horizontal_flip: true
    random_rotation: 10
    color_jitter:
      brightness: 0.2
      contrast: 0.2  
      saturation: 0.2
      hue: 0.1
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  
  val:
    resize: 256
    center_crop: 224
    normalize:
      mean: [0.485, 0.456, 0.406] 
      std: [0.229, 0.224, 0.225]

# 輸出設置
output:
  model_save_path: "best_cat_dog_model.pth"
  plot_save_path: "training_curves.png"
  log_interval: 10
  save_best_only: true
  
# 硬體設置
hardware:
  device: "auto"  # 可選: auto, cpu, cuda
  mixed_precision: false
  
# 早停設置
early_stopping:
  enabled: true
  patience: 5
  min_delta: 0.001
  
# 驗證設置  
validation:
  validate_every: 1  # 每幾個 epoch 驗證一次
  metrics: ["accuracy", "loss"]
