name: Upload Trained Model to Release

on:
  workflow_dispatch:  # 手動觸發
    inputs:
      release_name:
        description: 'Release 名稱'
        required: true
        default: 'trained-model-v1.0'
      model_description:
        description: '模型描述'
        required: false
        default: '貓狗分類器訓練完成的模型'

jobs:
  upload-model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # 從最近的 Artifacts 下載模型
    - name: Download latest trained model
      uses: actions/download-artifact@v4
      with:
        name: trained-cat-dog-model
        path: ./model-files/
        
    - name: Verify downloaded files
      run: |
        echo "下載的文件："
        ls -la ./model-files/
        
        if [ -f "./model-files/best_cat_dog_model.pth" ]; then
          echo "✅ 找到模型文件"
          file_size=$(stat -c%s "./model-files/best_cat_dog_model.pth")
          echo "模型大小: $((file_size / 1024 / 1024)) MB"
        else
          echo "❌ 未找到模型文件"
          exit 1
        fi
        
    - name: Create Release with Model
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.release_name }}
        name: ${{ github.event.inputs.release_name }}
        body: |
          🐱🐶 **貓狗分類器訓練完成模型**
          
          ${{ github.event.inputs.model_description }}
          
          **模型資訊：**
          - 架構: ResNet18
          - 訓練完成時間: ${{ github.run_started_at }}
          - Commit: ${{ github.sha }}
          
          **使用方法：**
          ```bash
          # 下載模型文件
          wget https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.release_name }}/best_cat_dog_model.pth
          
          # 執行預測
          python predict.py --model best_cat_dog_model.pth --image your_image.jpg
          ```
          
          **或使用快速預測工具：**
          ```bash
          python quick_predict.py --model-source github_release --create-test-images 10
          ```
        files: |
          ./model-files/best_cat_dog_model.pth
          ./model-files/training_curves.png
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
