: Train Cat-Dog Classifier

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install kaggle gdown

    - name: Download last checkpoint (if any)
      uses: dawidd6/action-download-artifact@v6
      with:
        name: ckpt
        path: ckpt_in
        search_artifacts: true
        if_no_artifact_found: ignore
        branch: main                # 依你的主要分支調整
        workflow_conclusion: completed


    - name: Build RESUME_ARG
      id: resume
      run: |
        if [ -f ckpt_in/checkpoint_latest.pth ]; then
          echo "resume=--resume ckpt_in/checkpoint_latest.pth" >> $GITHUB_OUTPUT
          echo "Found checkpoint_latest.pth, will resume."
        else
          echo "resume=" >> $GITHUB_OUTPUT
          echo "No checkpoint found, start fresh."
        fi

    # 你現有的資料下載＆整理（略）

    - name: Verify dataset structure
      run: |
        echo "檢查數據集結構..."
        ls -la file/kaggle_cats_vs_dogs_f/ || true
        ls -la file/kaggle_cats_vs_dogs_f/train/ || true
        ls -la file/kaggle_cats_vs_dogs_f/val/ || true

    - name: Train model (auto-stop before 6h)
      run: |
        echo "開始訓練模型..."
        python train_model.py \
          --data-dir file/kaggle_cats_vs_dogs_f \
          --architecture resnet34 \
          --max-epochs 200 \
          --save-every 5 \
          --max-wall-min 250 \
          ${{ steps.resume.outputs.resume }}

    - name: Upload checkpoint for next run
      uses: actions/upload-artifact@v4
      with:
        name: ckpt
        path: |
          checkpoint_latest.pth
          checkpoint_epoch*.pth
          checkpoint_best.pth
          TRAINING_COMPLETE.txt
          NEED_MORE.txt
        retention-days: 14

    # 僅在最終模型存在時才做測試與釋出
    - name: Test model predictions (val)
      if: ${{ hashFiles('best_cat_dog_model.pth') != '' }}
      run: |
        echo "測試模型預測（val）..."
        mkdir -p test_images
        cp file/kaggle_cats_vs_dogs_f/val/cat/*.jpg test_images/ 2>/dev/null || true
        cp file/kaggle_cats_vs_dogs_f/val/dog/*.jpg test_images/ 2>/dev/null || true
        python predict.py --model best_cat_dog_model.pth --folder test_images/

    - name: Upload trained model
      if: ${{ hashFiles('best_cat_dog_model.pth') != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: trained-cat-dog-model
        path: |
          best_cat_dog_model.pth
          overfit_training_curves.png
        retention-days: 30
